fix build error
error: The 'compilation' argument must be an instance of Compilation

resolve by adding webpack resolution to 5.91.0, which is the highest version referenced in the lock file across all dependencies. All other packages were using 5.80.0